function render(){
  const main=$('#main'), nav=$('#bottomNav'), roomLine=$('#roomLine');
  if(!state.loginVerified){ roomLine.classList.add('hidden'); nav.classList.add('hidden'); main.innerHTML=loginHTML(); bindLogin(); return; }
  if(state.room){ roomLine.classList.remove('hidden'); $('#roomCodeTop').textContent=state.room.code; $('#myIdentity').textContent=identityName(); } else roomLine.classList.add('hidden');
  if(!state.room){ nav.classList.add('hidden'); main.innerHTML=homeHTML(); bindHome(); return; }
  nav.classList.remove('hidden'); $$('.navbtn',nav).forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));
  if(state.tab==='setup'){ main.innerHTML=setupHTML(); bindSetup(); } else if(state.tab==='ledger'){ main.innerHTML=ledgerHTML(); bindLedger(); } else { state.tab='round'; main.innerHTML=roundHTML(); bindRound(); }
}
function loginHTML(){ return `<section class="card hero"><div class="fs11" style="opacity:.75;font-weight:900">MY GOLF LEDGER</div><h1>오늘 누가 쏴?</h1><p>내 이름으로 로그인하면 이 휴대폰은 자동으로 내 스코어 입력용 앱으로 설정됩니다.</p></section><section class="card"><h2>로그인</h2><div class="sub">아이디는 본인 이름, 공통 비밀번호는 <b>1234</b>입니다.</div><div class="stack"><div><label>아이디 · 이름</label><input id="loginName" maxlength="10" autocomplete="username" placeholder="예: 진우" value="${escapeHtml(identityName())}"></div><div><label>비밀번호</label><input id="loginPw" type="password" inputmode="numeric" maxlength="4" autocomplete="current-password" placeholder="1234"></div><button id="loginBtn" class="btn primary block">내 앱으로 로그인</button><div id="loginMsg"></div></div></section><section class="card"><h3>사용 방식</h3><div class="sub mb0">ROOM의 등록 이름과 로그인 이름이 같으면 자동 연결됩니다. 이름이 다르면 최초 1회 본인 이름을 선택하고, 이 휴대폰이 그 선택을 기억합니다.</div></section>`; }
function bindLogin(){ const go=async()=>{ const name=($('#loginName')?.value||'').trim(),pw=$('#loginPw')?.value||'',msg=$('#loginMsg'); if(!name){msg.innerHTML='<div class="notice error">이름을 입력하세요.</div>';return;} if(pw!==COMMON_PASSWORD){msg.innerHTML='<div class="notice error">비밀번호가 맞지 않습니다. 공통 비밀번호는 1234입니다.</div>';return;} state.identity={name};state.loginVerified=true;saveIdentity();if(state.session?.roomCode)await resumeSession();render();}; $('#loginBtn')?.addEventListener('click',go); $('#loginPw')?.addEventListener('keydown',e=>{if(e.key==='Enter')go()}); }
function homeHTML(){ const saved=state.session?.roomCode; return `<section class="card hero"><div class="fs11" style="opacity:.75;font-weight:900">${escapeHtml(identityName())}님의 골프 장부</div><h1>오늘 누가 쏴?<br>타수는 진짜, 정산은 자동.</h1><p>등록 이름과 로그인 이름이 같으면 자동 연결되고, 다르면 최초 1회만 본인을 선택하면 다음부터 자동 연결됩니다.</p></section><div class="grid2" style="margin-bottom:8px"><div class="notice success" style="margin:0"><b>● ${escapeHtml(identityName())}</b><br>내 앱으로 로그인됨</div><button id="logoutBtn" class="btn ghost">다른 이름으로 로그인</button></div>${!state.firebaseReady?`<div class="notice ${state.firebaseError?'error':''}"><b>${state.firebaseError?'Firebase 연결 실패':'실시간 연결 전'}</b><br>${state.firebaseError||'현재는 이 기기에서만 저장됩니다. 4명이 동시에 사용하려면 Firebase 실시간 연결이 필요합니다.'}</div>`:''}${saved?`<button id="resumeBtn" class="btn secondary block" style="margin-bottom:10px">이전 ROOM ${saved} 다시 열기</button>`:''}<section class="card"><h2>새 라운드 만들기</h2><div class="sub">1번 플레이어는 로그인한 본인으로 자동 고정됩니다. 동반자 이름은 실제 라운드에서 표시할 이름으로 입력하세요.</div><div class="stack"><div><label>라운드 이름</label><input id="gameTitle" value="오늘의 라운드" maxlength="30"></div>${[1,2,3,4].map((n,i)=>`<div class="playerset"><div class="avatar">${n}</div><input id="name${n}" value="${i===0?escapeHtml(identityName()):`동반자 ${n}`}" maxlength="10" ${i===0?'readonly':''}></div>`).join('')}<button id="createRoomBtn" class="btn primary block">ROOM 만들기</button></div></section>${state.firebaseReady?`<section class="card"><h2>ROOM 참가하기</h2><div class="sub"><b>${escapeHtml(identityName())}</b> 이름과 일치하면 자동 연결합니다. 다르면 등록된 4명 중 본인을 한 번만 선택하세요.</div><div class="grid2"><input id="joinCode" placeholder="ROOM CODE" maxlength="8" style="text-transform:uppercase"><button id="autoJoinBtn" class="btn primary">ROOM 참가</button></div><div id="joinSlots" class="mt12"></div></section>`:''}<section class="card"><h3>로그인 원칙</h3><div class="sub mb0">아이디는 이름, 비밀번호는 전원 1234입니다. 이 로그인은 결제·금융 보안용 계정이 아니라 <b>4명의 입력자를 구분하는 간편 식별 기능</b>입니다.</div></section>`; }
function bindHome(){ $('#createRoomBtn')?.addEventListener('click',createRoom);$('#autoJoinBtn')?.addEventListener('click',autoJoinRoom);$('#resumeBtn')?.addEventListener('click',async()=>{await resumeSession();render();});$('#logoutBtn')?.addEventListener('click',()=>{if(state.unsub){state.unsub();state.unsub=null;}state.room=null;state.myPlayerId=null;state.tab='home';state.identity=null;state.loginVerified=false;saveIdentity();render();}); }
async function createRoom(){ const names=[1,2,3,4].map(i=>($(`#name${i}`).value||`플레이어 ${i}`).trim());names[0]=identityName();if(names.some(n=>!n)){toast('플레이어 이름을 모두 입력하세요.');return;}if(!uniquePlayerNames(names)){toast('같은 ROOM에서는 플레이어 이름을 중복할 수 없습니다.');return;}const room=newRoom(names);room.title=$('#gameTitle').value.trim()||'오늘의 라운드';if(state.firebaseReady){room.players[0].claimedBy=state.uid;const{doc,setDoc}=state.fx;await setDoc(doc(state.db,'rooms',room.code),room);}else{room.code=rid();room.players[0].claimedBy='demo';localStorage.setItem(demoStorageKey,JSON.stringify(room));}state.room=room;state.myPlayerId='p1';state.session={roomCode:room.code,playerId:'p1',host:true,identityName:identityName()};saveSession();saveBinding(room.code,'p1');state.tab='setup';if(state.firebaseReady)subscribeRoom(room.code);render(); }
async function autoJoinRoom(){ const code=$('#joinCode').value.trim().toUpperCase();if(!code)return;const box=$('#joinSlots');box.innerHTML='<div class="muted fs12">ROOM 정보를 확인하는 중...</div>';try{const{doc,getDoc}=state.fx,ref=doc(state.db,'rooms',code),snap=await getDoc(ref);if(!snap.exists()){box.innerHTML='<div class="notice error">ROOM을 찾을 수 없습니다.</div>';return;}const room=snap.data(),players=room.players||[],matches=players.filter(p=>sameName(p.name,identityName()));if(matches.length===1){await claimSlotByLogin(code,matches[0].id,false);return;}if(matches.length>1){box.innerHTML='<div class="notice error">같은 이름이 2명 이상 등록되어 자동 연결할 수 없습니다. 아래에서 본인을 직접 선택하세요.</div>'+playerPickerHTML(players,code);bindPlayerPicker(code);return;}const binding=savedBinding(code),boundPlayer=binding&&players.find(p=>p.id===binding.playerId);if(boundPlayer){await claimSlotByLogin(code,boundPlayer.id,true);return;}box.innerHTML=`<div class="notice"><b>${escapeHtml(identityName())}</b>과 정확히 같은 등록 이름이 없습니다.<br>본인 이름을 한 번 선택하면 이 휴대폰이 기억합니다.</div>${playerPickerHTML(players,code)}`;bindPlayerPicker(code);}catch(e){box.innerHTML=`<div class="notice error">${escapeHtml(e.message)}</div>`} }
function playerPickerHTML(players,code){return `<div class="stack mt12">${players.map(p=>`<button class="btn secondary block playerPick" data-pick-player="${p.id}" data-room="${escapeHtml(code)}"><b>${escapeHtml(p.name)}</b>으로 연결</button>`).join('')}</div>`;}
function bindPlayerPicker(code){$$('.playerPick').forEach(b=>b.addEventListener('click',async()=>{if(!confirm(`${getPlayerNameFromPicker(b)}님이 본인이 맞습니까?\n이 선택은 이 휴대폰에 저장됩니다.`))return;await claimSlotByLogin(code,b.dataset.pickPlayer,true);}));}
function getPlayerNameFromPicker(btn){return(btn?.textContent||'').replace(/으로 연결\s*$/,'').trim();}
async function claimSlotByLogin(code,id,manual=false){const{doc,runTransaction}=state.fx,ref=doc(state.db,'rooms',code);try{let matchedName='';await runTransaction(state.db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('ROOM 없음');const data=snap.data(),players=data.players||[],idx=players.findIndex(p=>p.id===id);if(idx<0)throw new Error('플레이어를 찾을 수 없습니다.');if(!manual&&!sameName(players[idx].name,identityName()))throw new Error('로그인 이름과 ROOM 이름이 일치하지 않습니다.');if(players[idx].claimedBy&&players[idx].claimedBy!==state.uid)throw new Error('이미 다른 휴대폰에 연결된 플레이어입니다. 호스트가 설정에서 연결을 초기화한 뒤 다시 참가해 주세요.');matchedName=players[idx].name;players[idx].claimedBy=state.uid;tx.update(ref,{players,updatedAt:Date.now()});});state.session={roomCode:code,playerId:id,host:false,identityName:identityName()};state.myPlayerId=id;saveSession();saveBinding(code,id);state.tab='round';subscribeRoom(code);toast(`${matchedName||identityName()}님 앱으로 연결되었습니다.`);}catch(e){alert(e.message)}}
function setupHTML(){const editable=isHost()||!state.firebaseReady;return `<div class="setupnav"><button class="btn ${state.setupTab==='players'?'active':'ghost'}" data-st="players">플레이어</button><button class="btn ${state.setupTab==='course'?'active':'ghost'}" data-st="course">18홀</button><button class="btn ${state.setupTab==='rules'?'active':'ghost'}" data-st="rules">내기 규칙</button></div>${!editable?`<div class="notice">설정은 ROOM 생성자만 변경할 수 있습니다. 현재 설정은 실시간으로 확인할 수 있습니다.</div>`:''}${state.setupTab==='players'?playersSetupHTML(editable):state.setupTab==='course'?courseSetupHTML(editable):rulesSetupHTML(editable)}<section class="card"><div class="grid2"><button id="copyRoom" class="btn secondary">ROOM 코드 복사</button>${editable?`<button id="startRound" class="btn primary">${state.room.status==='active'?'라운드로 이동':'라운드 시작'}</button>`:`<button id="goRound" class="btn primary">라운드 보기</button>`}</div></section>`;}
function setupSaveButton(label,editable){if(!editable)return'';return `<button class="btn block setup-save ${state.setupDirty?'primary':'saved'}" data-save-setup>${state.setupDirty?`${label} 저장`:`✓ ${label} 저장됨`}</button>`;}
function playersSetupHTML(editable){return `<section class="card"><h2>플레이어 4명</h2><div class="sub">플레이어 이름은 라운드에 표시할 이름입니다. 로그인 이름과 같으면 자동 연결되고, 다르면 동반자가 최초 1회 본인 이름을 선택하면 이후 이 휴대폰에서 자동 연결됩니다.</div><div class="stack">${state.room.players.map((p,i)=>`<div class="playerset"><div class="avatar">${i+1}</div><div><input class="playerNameInput" data-id="${p.id}" value="${escapeHtml(p.name)}" maxlength="10" ${editable&&p.id!==state.myPlayerId&&!p.claimedBy?'':(p.id===state.myPlayerId?'readonly':'disabled')}><div class="fs11 muted mt8">${p.id===state.myPlayerId?'● 내 로그인 이름 · 변경 불가':p.claimedBy?'● 본인 앱 연결됨':'○ 아직 미참가'}</div>${editable&&p.claimedBy&&p.id!==state.myPlayerId?`<button class="btn ghost small mt8 resetClaim" data-reset-claim="${p.id}">연결 초기화</button>`:''}</div></div>`).join('')}</div>${setupSaveButton('플레이어',editable)}</section>`;}
function courseSetupHTML(editable){const total=state.room.pars.reduce((a,b)=>a+b,0);return `<section class="card"><h2>18홀 구성 <span class="muted fs12">TOTAL PAR ${total}</span></h2><div class="sub">각 홀의 PAR를 3·4·5 중 선택하세요.</div><div class="coursegrid">${state.room.pars.map((par,i)=>`<div class="holebox"><b>${i+1}H</b><div class="parselect">${[3,4,5].map(v=>`<button class="parBtn ${par===v?'on':''}" data-hole="${i+1}" data-par="${v}" ${editable?'':'disabled'}>${v}</button>`).join('')}</div></div>`).join('')}</div>${setupSaveButton('코스',editable)}</section>`;}
function rulesSetupHTML(editable){const r=state.room.rules;return `<section class="card"><h2>기본 금액</h2><div class="grid2"><div><label>1타당 금액</label><input class="ruleNum" data-key="baseAmount" type="number" min="0" step="100" value="${r.baseAmount}" ${editable?'':'disabled'}></div><div><label>타수차 상한 (0=없음)</label><input class="ruleNum" data-key="maxDiff" type="number" min="0" max="20" value="${r.maxDiff}" ${editable?'':'disabled'}></div><div><label>버디 보너스 / 1인당</label><input class="ruleNum" data-key="birdieBonus" type="number" min="0" step="100" value="${r.birdieBonus}" ${editable?'':'disabled'}></div><div><label>이글 이상 보너스 / 1인당</label><input class="ruleNum" data-key="eagleBonus" type="number" min="0" step="100" value="${r.eagleBonus}" ${editable?'':'disabled'}></div></div></section><section class="card"><h2>배판 적용 방식</h2><div class="sub">모임마다 다른 부분이라 시작 전에 명확히 정합니다.</div><label>배판 발생 시점</label><div class="seg"><button class="timingBtn ${r.doubleTiming==='current'?'on':''}" data-v="current" ${editable?'':'disabled'}>해당 홀 즉시 2배</button><button class="timingBtn ${r.doubleTiming==='next'?'on':''}" data-v="next" ${editable?'':'disabled'}>다음 홀 2배</button></div><div class="grid2 mt12"><div><label>최대 배수</label><select id="maxMultiplier" ${editable?'':'disabled'}>${[2,4,8,16].map(v=>`<option value="${v}" ${r.maxMultiplier===v?'selected':''}>${v}배</option>`).join('')}</select></div><div><label>복수 조건</label><select id="stackMode" ${editable?'':'disabled'}><option value="0" ${!r.multiConditionStack?'selected':''}>조건 여러 개여도 2배</option><option value="1" ${r.multiConditionStack?'selected':''}>조건마다 ×2 누적</option></select></div></div>${r.doubleTiming==='next'?`<div class="switchrow"><div class="switchcopy"><strong>연속 배판 누적</strong><span>전 홀도 배판이고 또 조건이 나오면 2→4→8배로 누적</span></div>${switchHtml('consecutiveCarry',r.consecutiveCarry,editable)}</div>`:''}</section><section class="card"><h2>배판 조건</h2>${ruleSwitch('triple','트리플보기 이상','누군가 PAR 대비 +3 이상이면 배판',r.triple,editable)}${ruleSwitch('doublePar','더블파(양파)','누군가 해당 홀 PAR의 2배 타수를 기록',r.doublePar,editable)}${ruleSwitch('birdieTrigger','버디 이상','버디·이글 등이 나오면 배판',r.birdieTrigger,editable)}${ruleSwitch('threeTie','3명 동타','4명 중 정확히 3명이 같은 타수',r.threeTie,editable)}${ruleSwitch('allTieCarry','전원 동타 이월 배판','4명 모두 동타면 이번 홀은 0원, 다음 홀은 자동 2배',r.allTieCarry!==false,editable)}${ruleSwitch('manualTriggerEnabled','기타/OB 등 수동 배판','점수만으로 판단할 수 없는 상황은 홀 화면에서 직접 체크',r.manualTriggerEnabled,editable)}${setupSaveButton('내기 규칙',editable)}</section><section class="card"><h3>계산 기준</h3><div class="sub mb0">A가 4타, B가 6타이고 타당 1,000원이라면 B가 A에게 2,000원. 배판 2배면 4,000원입니다. 4명 전원이 동타면 그 홀은 정산 없이 0원이며 다음 홀은 자동 2배로 시작합니다. 버디/이글 보너스를 설정하면 해당 플레이어가 나머지 3명에게서 각각 보너스를 추가로 받습니다.</div></section>`;}
function switchHtml(key,on,editable){return `<label class="switch"><input class="ruleBool" data-key="${key}" type="checkbox" ${on?'checked':''} ${editable?'':'disabled'}><span class="slider"></span></label>`;}
function ruleSwitch(key,title,desc,on,editable){return `<div class="switchrow"><div class="switchcopy"><strong>${title}</strong><span>${desc}</span></div>${switchHtml(key,on,editable)}</div>`;}
function markSetupDirty(){state.setupDirty=true;}
async function saveSetup(){const names=state.room.players.map(p=>(p.name||'').trim());if(names.some(n=>!n)){toast('플레이어 이름을 모두 입력하세요.');return;}if(!uniquePlayerNames(names)){toast('플레이어 이름은 서로 달라야 합니다.');return;}await persistRoom();state.setupDirty=false;render();toast('설정이 저장되었습니다.');}
function bindSetup(){
  $$('.setupnav button').forEach(b=>b.addEventListener('click',()=>{state.setupTab=b.dataset.st;render()}));
  $$('.playerNameInput').forEach(i=>i.addEventListener('input',()=>{const p=getPlayer(i.dataset.id);p.name=i.value.trim()||p.name;markSetupDirty();const btn=$('[data-save-setup]');if(btn){btn.textContent='플레이어 저장';btn.classList.add('primary');btn.classList.remove('saved')}}));
  $$('.resetClaim').forEach(b=>b.addEventListener('click',async()=>{const p=getPlayer(b.dataset.resetClaim);if(!p||!isHost())return;if(!confirm(`${p.name}님의 휴대폰 연결을 초기화할까요?\n다음 참가 시 다시 본인을 선택해야 합니다.`))return;const players=clone(state.room.players),idx=players.findIndex(x=>x.id===p.id);if(idx<0)return;players[idx].claimedBy=null;try{await persistRoom({players,updatedAt:Date.now()});state.room.players=players;toast('연결을 초기화했습니다.');}catch(e){toast('초기화에 실패했습니다. 인터넷 연결을 확인해 주세요.');}}));
  $$('.parBtn').forEach(b=>b.addEventListener('click',()=>{state.room.pars[+b.dataset.hole-1]=+b.dataset.par;markSetupDirty();render()}));
  $$('.ruleNum').forEach(i=>i.addEventListener('input',()=>{state.room.rules[i.dataset.key]=Math.max(0,+i.value||0);markSetupDirty();const btn=$('[data-save-setup]');if(btn){btn.textContent='내기 규칙 저장';btn.classList.add('primary');btn.classList.remove('saved')}}));
  $$('.ruleBool').forEach(i=>i.addEventListener('change',()=>{state.room.rules[i.dataset.key]=i.checked;markSetupDirty();render()}));
  $$('.timingBtn').forEach(b=>b.addEventListener('click',()=>{state.room.rules.doubleTiming=b.dataset.v;markSetupDirty();render()}));
  $('#maxMultiplier')?.addEventListener('change',e=>{state.room.rules.maxMultiplier=+e.target.value;markSetupDirty();render()});$('#stackMode')?.addEventListener('change',e=>{state.room.rules.multiConditionStack=e.target.value==='1';markSetupDirty();render()});$$('[data-save-setup]').forEach(b=>b.addEventListener('click',saveSetup));$('#copyRoom')?.addEventListener('click',()=>copyText(state.room.code,'ROOM 코드가 복사되었습니다.'));$('#startRound')?.addEventListener('click',async()=>{state.room.status='active';state.room.currentHole=firstIncomplete();await persistRoom();state.setupDirty=false;state.tab='round';render()});$('#goRound')?.addEventListener('click',()=>{state.tab='round';render()});
}
