function roundHTML(){
  const h=currentHole(), par=state.room.pars[h-1], L=holeLedger(h), cum=cumulativeLedger(h), complete=holeComplete(h);
  const allTie=L.allTie===true, prevAllTie=h>1 && (state.room.rules.allTieCarry !== false) && allTieHole(h-1);
  const triggers=state.room.rules.doubleTiming==='current'?triggerInfo(h):(h>1?triggerInfo(h-1):[]);
  const displayTriggers=[...(prevAllTie?['전 홀 전원 동타 이월']:[]),...triggers];
  const triggerText=allTie ? (h<18?'전원 동타 · 이번 홀 정산 0원 · 다음 홀 자동 ×2':'전원 동타 · 이번 홀 정산 0원 · 라운드 종료') : (displayTriggers.length?`배판: ${[...new Set(displayTriggers)].join(' · ')}`:'배판 조건 없음');
  const myNet=L.net[state.myPlayerId]||0, cumMy=cum.net[state.myPlayerId]||0, saved=confirmedCount(h);
  return `<div class="statusbar"><div class="names">${state.room.players.map(p=>{const c=cumulativeToPar(p.id);return `<span class="tinyplayer ${p.claimedBy?'online':''}">${p.name}<b>${c.holes?parLabel(c.diff):'–'}</b></span>`}).join('')}</div><div class="roundprogress">${completedCount()}/18H</div></div><section class="card holehero"><div class="holehead"><div><div class="par">PAR ${par}</div><div class="holeid">${h} HOLE</div></div><div class="mult ${allTie||L.mult===1?'normal':''}">${allTie?'0원':`× ${L.mult}`}</div></div><div class="trigger">${triggerText}</div><div class="holemoney"><div class="miniStat"><span>이번 홀 내 손익</span><strong>${complete?signed(myNet):'대기'}</strong></div><div class="miniStat"><span>현재까지 누적</span><strong>${signed(cumMy)}</strong></div></div></section><section class="card scorecard"><div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">스코어</h2><span class="fs11 ${complete?'plus':'muted'}">${complete?'● 4/4 정산 확정':`○ ${saved}/4 입력완료`}</span></div>${state.room.players.map(p=>scoreRowHTML(h,p,par)).join('')}${state.room.rules.manualTriggerEnabled?`<div class="switchrow" style="padding:7px 0 1px;margin-top:2px"><div class="switchcopy"><strong style="font-size:11px">기타 사유 배판</strong><span>OB 등 수동 조건</span></div><label class="switch"><input id="manualDouble" type="checkbox" ${state.room.manualDouble?.[`h${h}`]?'checked':''} ${isHost()||!state.firebaseReady?'':'disabled'}><span class="slider"></span></label></div>`:''}${complete?`<div class="score-summary">${state.room.players.map(p=>{const n=L.net[p.id]||0;return `<div><span>${p.name}</span><strong class="${n>0?'plus':n<0?'minus':'zero'}">${signed(n)}</strong></div>`}).join('')}</div>`:`<div class="center muted" style="font-size:9px;margin-top:7px">4명 모두 ‘입력 저장’을 누르면 이번 홀 금액이 확정됩니다.</div>`}</section><section class="card roundnav"><div class="roundnavtop"><button id="prevHole" class="btn ghost small" ${h===1?'disabled':''}>← 이전</button><b>${h}/18</b><button id="nextHole" class="btn secondary small" ${h===18?'disabled':''}>다음 →</button></div><div class="holetrack">${Array.from({length:18},(_,i)=>{const n=i+1;return `<button class="hchip ${n===h?'current':holeComplete(n)?'done':'pending'}" data-hole="${n}">${n}</button>`}).join('')}</div></section>`;
}
function scoreRowHTML(h,p,par){const v=scoreOf(h,p.id),editable=canEditPlayer(p.id),desc=classify(v,par),isMine=p.id===state.myPlayerId,confirmed=isConfirmed(h,p.id);const badge=confirmed?'<span class="confirm-badge done">완료</span>':Number.isFinite(v)?'<span class="confirm-badge draft">저장 전</span>':'<span class="confirm-badge">대기</span>';return `<div class="scorerow ${isMine?'myrow':''}"><div class="scoretop"><div><div class="pname">${p.name}${isMine?' <span class="fs11 plus">ME</span>':''}</div><div class="psub">${Number.isFinite(v)?desc:'아직 미입력'} · 누적 ${cumulativeToPar(p.id).holes?parLabel(cumulativeToPar(p.id).diff):'–'}</div></div><div class="score-number">${Number.isFinite(v)?v:'-'}</div>${badge}</div>${editable?`<div class="score-actions">${[-1,0,1,2,3].map(d=>{const sv=par+d,label=d===-1?'버디':d===0?'파':d===1?'보기':d===2?'더블':'트리플';return `<button class="score-choice ${v===sv?'on':''}" data-qplayer="${p.id}" data-score="${sv}">${label}</button>`}).join('')}<button class="score-choice other" data-other="${p.id}">기타</button></div><button class="save-score ${confirmed?'saved':''}" data-save-score="${p.id}" ${Number.isFinite(v)?'':'disabled'}>${confirmed?'✓ 입력 완료':'입력 저장'}</button>`:''}</div>`;}
function moneyCard(p,n){return `<div class="moneycard"><div class="name">${p.name}</div><div class="amt ${n>0?'plus':n<0?'minus':'zero'}">${signed(n)}</div></div>`;}
function pairSummaryHTML(pair){const rows=[];state.room.players.forEach((a,i)=>state.room.players.slice(i+1).forEach(b=>{const v=pair[`${a.id}_${b.id}`]||0;if(Math.abs(v)<.5)rows.push(`<div class="pair">${a.name} = ${b.name}<b>0원</b></div>`);else{const winner=v>0?a:b,loser=v>0?b:a;rows.push(`<div class="pair">${loser.name} → ${winner.name}<b>${fmt(v)}</b></div>`);}}));return `<div class="pairgrid mt12">${rows.join('')}</div>`;}
function openOtherScores(playerId){const h=currentHole(),par=state.room.pars[h-1];const opts=[{d:-3,l:'알바트로스'},{d:-2,l:'이글'},{d:4,l:'+4'},{d:5,l:'+5'},{d:6,l:'+6'},{d:7,l:'+7'},{d:8,l:'+8'}];const root=$('#modalRoot');root.innerHTML=`<div class="modal" id="scoreModal"><div class="sheet"><div class="sheethead"><div><h2 style="margin:0">기타 스코어</h2><div class="fs11 muted mt8">PAR ${par} · 버튼을 바로 선택하세요.</div></div><button class="x" id="closeScoreModal">×</button></div><div class="grid2">${opts.map(o=>`<button class="btn secondary otherScore" data-score="${clamp(par+o.d,1,20)}">${o.l} · ${clamp(par+o.d,1,20)}타</button>`).join('')}</div></div></div>`;$('#closeScoreModal')?.addEventListener('click',()=>root.innerHTML='');$$('.otherScore',root).forEach(b=>b.addEventListener('click',async()=>{root.innerHTML='';await setScore(playerId,+b.dataset.score)}));}
function bindRound(){ $$('[data-qplayer]').forEach(b=>b.addEventListener('click',()=>setScore(b.dataset.qplayer,+b.dataset.score)));$$('[data-other]').forEach(b=>b.addEventListener('click',()=>openOtherScores(b.dataset.other)));$$('[data-save-score]').forEach(b=>b.addEventListener('click',()=>confirmScore(b.dataset.saveScore)));$('#manualDouble')?.addEventListener('change',async e=>{state.room.manualDouble||={};state.room.manualDouble[`h${currentHole()}`]=e.target.checked;await persistRoom();render()});$('#prevHole')?.addEventListener('click',()=>goHole(currentHole()-1));$('#nextHole')?.addEventListener('click',()=>goHole(currentHole()+1));$$('.hchip').forEach(b=>b.addEventListener('click',()=>goHole(+b.dataset.hole))); }
async function setScore(playerId,v){ if(!canEditPlayer(playerId)||state.busy)return;const h=currentHole(),prev=scoreOf(h,playerId),prevConfirmed=isConfirmed(h,playerId);setScoreLocal(h,playerId,v);setConfirmedLocal(h,playerId,false);render();if(state.firebaseReady){state.busy=true;try{const sp=`scores.h${h}.${playerId}`,cp=`confirmed.h${h}.${playerId}`;await persistRoom({[sp]:v,[cp]:false,updatedAt:Date.now()});}catch(e){setScoreLocal(h,playerId,prev);setConfirmedLocal(h,playerId,prevConfirmed);toast('스코어 저장에 실패했습니다. 인터넷 연결을 확인해 주세요.');render();}finally{state.busy=false;}}else{saveDemo();render();} }
async function confirmScore(playerId){ if(!canEditPlayer(playerId)||state.busy)return;const h=currentHole();if(!Number.isFinite(scoreOf(h,playerId))){toast('먼저 스코어를 선택하세요.');return;}const prevConfirmed=isConfirmed(h,playerId);setConfirmedLocal(h,playerId,true);render();if(state.firebaseReady){state.busy=true;try{const cp=`confirmed.h${h}.${playerId}`;await persistRoom({[cp]:true,updatedAt:Date.now()});}catch(e){setConfirmedLocal(h,playerId,prevConfirmed);toast('입력 완료 저장에 실패했습니다. 인터넷 연결을 확인해 주세요.');render();}finally{state.busy=false;}}else{saveDemo();render();} }
async function goHole(h){state.room.currentHole=clamp(h,1,18);if(state.firebaseReady&&isHost())await persistRoom({currentHole:state.room.currentHole,updatedAt:Date.now()});else saveDemo();render();}
