function ledgerHTML(){
  const upTo=18,cum=cumulativeLedger(upTo),transfers=minimalTransfers(cum.net),me=state.myPlayerId,rel=relativePairs(me,cum.pair),complete=completedCount();
  return `<section class="card"><div style="display:flex;justify-content:space-between;align-items:start"><div><div class="fs11 muted">${state.room.title}</div><h2 style="margin:3px 0 0">누적 정산</h2></div><button id="copySummary" class="copybtn">결과 복사</button></div><div class="moneygrid mt12">${state.room.players.map(p=>moneyCard(p,cum.net[p.id]||0)).join('')}</div><div class="sub mt12 mb0">${complete}/18홀 입력 완료 · 모든 완료 홀을 기준으로 자동 합산</div></section><section class="card"><h2>내가 누구에게 받거나 줄 돈</h2>${rel.map(r=>{const o=getPlayer(r.other);return `<div class="transfer"><div class="who">${r.amt>0?`<b>${o.name}</b>에게 받을 금액`:r.amt<0?`<b>${o.name}</b>에게 줄 금액`:`<b>${o.name}</b>과 정산 없음`}</div><strong class="${r.amt>0?'plus':r.amt<0?'minus':'zero'}">${signed(r.amt)}</strong></div>`}).join('')}</section><section class="card"><h2>최소 송금 정산</h2><div class="sub">상대별 거래를 모두 상계해서 실제 이체 횟수를 줄인 결과입니다.</div>${transfers.length?transfers.map(t=>`<div class="transfer"><div class="who"><b>${getPlayer(t.from).name}</b> <span class="arrow">→</span> <b>${getPlayer(t.to).name}</b></div><strong>${fmt(t.amt)}</strong></div>`).join(''):`<div class="center muted fs12">현재 정산할 금액이 없습니다.</div>`}</section><section class="card"><h2>상대별 누적 원장</h2>${pairSummaryHTML(cum.pair)}</section>`;
}
function bindLedger(){ $('#copySummary')?.addEventListener('click',()=>copyText(summaryText(),'정산 결과가 복사되었습니다.')); }
function summaryText(){ const cum=cumulativeLedger(18),transfers=minimalTransfers(cum.net);return `[${state.room.title}] 골프 정산\nROOM ${state.room.code}\n\n`+state.room.players.map(p=>`${p.name}: ${signed(cum.net[p.id]||0)}`).join('\n')+`\n\n[최소 송금]\n`+(transfers.length?transfers.map(t=>`${getPlayer(t.from).name} → ${getPlayer(t.to).name}: ${fmt(t.amt)}`).join('\n'):'정산 없음'); }
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
async function copyText(text,msg='복사했습니다.'){try{await navigator.clipboard.writeText(text);toast(msg)}catch{prompt('복사하세요',text)}}
function toast(msg){const root=$('#modalRoot');root.innerHTML=`<div class="modal" id="toastModal"><div class="sheet" style="padding-top:14px"><div class="center" style="font-weight:900">${escapeHtml(msg)}</div></div></div>`;setTimeout(()=>root.innerHTML='',900);}
$('#bottomNav').addEventListener('click',e=>{const b=e.target.closest('.navbtn');if(!b)return;state.tab=b.dataset.tab;render()});
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
(async()=>{ await initFirebase(); render(); })();
